### PR TITLE
17826 - CSR: Special resolution section error handing

### PR DESCRIPTION
**Pull request by Jxio**
*Issue #:* [/bcgov/entity17826](https://github.com/bcgov/entity/issues/17826)

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-edit-dev--pr-530-qqco1vni.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-edit-dev--pr-530-qqco1vni.web.app

**Review by JazzarKarim — APPROVED** [review]
LGTM Jia! 👍

**Review by severinbeauvais — APPROVED** [review]
LGTM

**Pull request merged**
