### PR TITLE
24040 Fix Alteration of Company Type Options for BEN/CBEN

### PR DESCRIPTION
**Pull request by meawong**
*Issue #:* /bcgov/entity#24040

*Description of changes:*
- remove CC option from allowed business alteration types for BEN businesses
- remove CCC option from allowed business alteration types for CBEN businesses
- update patch version

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-edit-dev--pr-593-nzrgwlvx.web.app

**Comment by meawong** [comment]
Numbered BEN business: https://business-edit-dev--pr-593-nzrgwlvx.web.app/BC0883647/alteration?accountid=3627
Numbered CBEN business: https://business-edit-dev--pr-593-nzrgwlvx.web.app/C9900823/alteration?accountid=3627
Named BEN business: https://business-edit-dev--pr-593-nzrgwlvx.web.app/BC0883657/alteration?accountid=3627
Named CBEN business: https://business-edit-dev--pr-593-nzrgwlvx.web.app/C9900826/alteration?accountid=3627

**Review by severinbeauvais — COMMENTED** [review]
LGTM

**Review by severinbeauvais — APPROVED** [review]

**Review by ArwenQin — APPROVED** [review]
Looks good!

**Review by ketaki-deodhar — APPROVED** [review]
Looks good!

**Pull request merged**
