### PR TITLE
15080-Unit tests for Extension & Conversion Summary page

### PR DESCRIPTION
**Pull request by ketaki-deodhar**
*Issue #:* /bcgov/entity#15080

*Description of changes:*

Unit tests for Extension & Conversion Summary page

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Review by severinbeauvais — APPROVED** [review]
Nicely done. Thanks!

Please wait for more reviews before merging.

**Comment by ketaki-deodhar** [comment]
> Nicely done. Thanks!
> 
> Please wait for more reviews before merging.

Thank you for all the help Sev!

**Review by jonathan-longe — APPROVED** [review]
Good work @ketaki-deodhar

**Review by JazzarKarim — APPROVED** [review]
A great learning opportunity for me here!

**Pull request merged**
