### PR TITLE
18495 - Fix corrections with no SR causing error

### PR DESCRIPTION
**Pull request by AbrahamRostampoor**
*Issue #:*https://github.com/bcgov/entity/issues/18495

*Description of changes:*
- Resolved SR coop correction crash 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by seeker25** [comment]
Trying this locally now

**Comment by Jxio** [comment]
this gonna handle by https://github.com/bcgov/business-edit-ui/pull/551

**Pull request closed without merging**
