### PR TITLE
Feature 13968 Certify block must be editable for SBC staff on the cha…

### PR DESCRIPTION
**Pull request by ritvick**
…nge filing

*Issue #:* /bcgov/entity/issues/13968

*Description of changes:*
Certify block must be editable for SBC staff on the change filing

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by ritvick** [comment]
@severinbeauvais / other devs,  is this the right place to make this change? or shall we have another parameter passed to Certify component isSbcStaff, and add the logic inside that shared component?
What do you think?

**Review by severinbeauvais — APPROVED** [review]
Looks good but please update the app version.

**Comment by severinbeauvais** [comment]
> @severinbeauvais / other devs, is this the right place to make this change? or shall we have another parameter passed to Certify component isSbcStaff, and add the logic inside that shared component? What do you think?

I think this is fine. At the moment, the Certify component doesn't need to know what kind of staff it is, so just using a single prop is fine. It's good to keep each component as independent/dumb/simple as possible :)

**Review by lambert-alex — APPROVED** [review]
LGTM

**Review by lambert-alex — APPROVED** [review]

**Review by severinbeauvais — COMMENTED** [review]
This code change looks fine to me, but please update the app version in package.json and then run `npm i` and commit both package files.

**Review by severinbeauvais — APPROVED** [review]

**Pull request merged**
