### PR TITLE
18495 - Bug Fix - Show Resolution Section when not Correction Filing

### PR DESCRIPTION
**Pull request by Jxio**
*Issue #:* [/bcgov/entity18495 ](https://github.com/bcgov/entity/issues/18495) [18622](https://github.com/bcgov/entity/issues/18622)

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Review by JazzarKarim — APPROVED** [review]
LGTM Jia!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-edit-dev--pr-552-t8mwhlyq.web.app

**Review by seeker25 — APPROVED** [review]

**Pull request merged**
