### PR TITLE
17347 - Add additional fields to Correction

### PR DESCRIPTION
**Pull request by Jxio**
*Issue #:* [/bcgov/entity17347](https://github.com/bcgov/entity/issues/17347)
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-edit-dev--pr-529-gdpeqhc4.web.app

**Comment by seeker25** [comment]
looks good so far

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-edit-dev--pr-529-gdpeqhc4.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-edit-dev--pr-529-gdpeqhc4.web.app

**Review by severinbeauvais — APPROVED** [review]
Well done! Looks good to me.

**Review by JazzarKarim — APPROVED** [review]
Looks great Jia! 👍

**Pull request merged**
