### PR TITLE
17347 - Add in directors for corrections for CP.

### PR DESCRIPTION
**Pull request by seeker25**
*Issue #:* /bcgov/entity#17347

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://business-edit-dev--pr-536-cc3p52um.web.app

**Review by Jxio — APPROVED** [review]
LGTM!

**Review by JazzarKarim — APPROVED** [review]
LGTM Travis!

**Pull request merged**
