### PR TITLE
13058 Update Common Completing Party

### PR DESCRIPTION
**Pull request by lewischenstudio**
*Issue #:* [/bcgov/entity#13058](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/13058)

*Description of changes:*
- updated common completing party version
- added unit test template for later

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Review by severinbeauvais — APPROVED** [review]
Looks good.

Should this go to Test ASAP? Let me know and also please tag your ticket to a release.

**Review by lambert-alex — APPROVED** [review]
LGTM!

**Comment by lewischenstudio** [comment]
> Looks good.
> 
> Should this go to Test ASAP? Let me know and also please tag your ticket to a release.

Thanks. This can go to test, as the first and middle names match the new schemas. I'll need Argus to check for Colin database for the last checkbox of the ticket, so this ticket might be 14.b.

**Comment by severinbeauvais** [comment]
> > Looks good.
> > Should this go to Test ASAP? Let me know and also please tag your ticket to a release.
> 
> Thanks. This can go to test, as the first and middle names match the new schemas. I'll need Argus to check for Colin database for the last checkbox in the ticket, so this ticket might be 14.2b.

I was wondering if this should go in the latest release that went to Test today (and would require a re-deploy). It doesn't sound like it.

**Comment by lewischenstudio** [comment]
> > > Looks good.
> > > Should this go to Test ASAP? Let me know and also please tag your ticket to a release.
> > 
> > 
> > Thanks. This can go to test, as the first and middle names match the new schemas. I'll need Argus to check for Colin database for the last checkbox in the ticket, so this ticket might be 14.2b.
> 
> I was wondering if this should go in the latest release that went to Test today (and would require a re-deploy). It doesn't sound like it.

I think this can wait a little. Just to be safe to hear from Argus that Colin db is synced .

**Pull request merged**
