### PR TITLE
15861 update sentry vue sdk

### PR DESCRIPTION
**Pull request by bolyachevets**
*Issue #: [15861](https://github.com/bcgov/entity/issues/15861)

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://business-edit-dev--pr-492-r93fbzr5.web.app

**Comment by severinbeauvais** [comment]
Please fill in the ticket number (same with other PR), so that this PR is automatically linked to the ticket.

**Review by severinbeauvais — APPROVED** [review]

**Comment by severinbeauvais** [comment]
I have restarted the linting and testing-coverage checks a couple of times and they still fail.

Make sure these pass before this PR is merged.

**Comment by pwei1018** [comment]
Temporary Url for review: https://business-edit-dev--pr-492-r93fbzr5.web.app

**Pull request merged**
